spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/${DB_NAME:flight_service_db}
    username: ${DB_USER:flight_user}
    password: ${DB_PASSWORD:flight_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # nunca "update" en real; usa Flyway/Liquibase para migraciones
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect